//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAccessContext : DbContext
    {
        public DataAccessContext()
            : base("name=DataAccessContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eloes> eloes { get; set; }
        public virtual DbSet<game_systems> game_systems { get; set; }
        public virtual DbSet<log_admin> log_admin { get; set; }
        public virtual DbSet<log_pwchange> log_pwchange { get; set; }
        public virtual DbSet<pairings> pairings { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
