//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAccessContext : DbContext
    {
        public DataAccessContext()
            : base("name=DataAccessContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eloes> eloes { get; set; }
        public virtual DbSet<game_systems> game_systems { get; set; }
        public virtual DbSet<log_admin> log_admin { get; set; }
        public virtual DbSet<log_pwchange> log_pwchange { get; set; }
        public virtual DbSet<pairings> pairings { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
