//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eloes
    {
        public int uid { get; set; }
        public int gid { get; set; }
        public int elo { get; set; }
        public int id { get; set; }
    
        public virtual game_systems game_systems { get; set; }
        public virtual users users { get; set; }
    }
}
