//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eloes
    {
        public int uid { get; set; }
        public int gid { get; set; }
        public int elo { get; set; }
        public int id { get; set; }
    
        public virtual game_systems game_systems { get; set; }
        public virtual users users { get; set; }
    }
}
