//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_admin
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int uid_affected { get; set; }
        public int uid_performed { get; set; }
        public string changed_from { get; set; }
        public string changed_to { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
