//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_pwchange
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int uid_ { get; set; }
        public int admin_id { get; set; }
        public string pw_old { get; set; }
        public string pw_new { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
