//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pairings
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int uid1 { get; set; }
        public int status1 { get; set; }
        public int uid2 { get; set; }
        public int status2 { get; set; }
        public int game_system_id { get; set; }
        public int result { get; set; }
    
        public virtual game_systems game_systems { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
