//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrettPit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pairings
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int uid1 { get; set; }
        public int status1 { get; set; }
        public int uid2 { get; set; }
        public int status2 { get; set; }
        public int game_system_id { get; set; }
        public int result { get; set; }
    
        public virtual game_systems game_systems { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
